-- MySQL Script generated by MySQL Workbench
-- Sun Dec 30 00:45:33 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema CarRental
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema CarRental
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `CarRental` DEFAULT CHARACTER SET utf8 ;
USE `CarRental` ;

-- -----------------------------------------------------
-- Table `CarRental`.`cars`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `CarRental`.`cars` (
  `tag_number` CHAR(8) NOT NULL,
  `model` VARCHAR(255) NOT NULL,
  `car_id` INT NOT NULL AUTO_INCREMENT,
  `make` VARCHAR(255) NOT NULL,
  `car_year` YEAR(4) NOT NULL,
  `category` CHAR(1) NOT NULL,
  `mp3_layer` TINYINT NULL,
  `dvd_player` TINYINT NULL,
  `air_conditioner` TINYINT NULL,
  `navigation` TINYINT NULL,
  `available` TINYINT NOT NULL,
  PRIMARY KEY (`car_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `CarRental`.`customers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `CarRental`.`customers` (
  `client_name` VARCHAR(255) NOT NULL,
  `customer_id` INT NOT NULL AUTO_INCREMENT,
  `client_phone` VARCHAR(10) NULL,
  `address` VARCHAR(255) NOT NULL,
  `zip_code` INT(4) NULL,
  `license_number` VARCHAR(10) NOT NULL,
  `country` VARCHAR(255) NOT NULL,
  `city` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`customer_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `CarRental`.`rates`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `CarRental`.`rates` (
  `rate_id` INT NOT NULL AUTO_INCREMENT,
  `category` CHAR(1) NOT NULL,
  `daily` FLOAT NOT NULL,
  `weekly` FLOAT NOT NULL,
  `monthly` FLOAT NOT NULL,
  PRIMARY KEY (`rate_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `CarRental`.`employees`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `CarRental`.`employees` (
  `employee_id` INT NOT NULL AUTO_INCREMENT,
  `employee_number` INT UNSIGNED NOT NULL,
  `first_name` VARCHAR(255) NOT NULL,
  `last_name` VARCHAR(255) NOT NULL,
  `hourly_salary` FLOAT NOT NULL,
  PRIMARY KEY (`employee_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `CarRental`.`orders`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `CarRental`.`orders` (
  `order_id` INT NOT NULL AUTO_INCREMENT,
  `employee_id` INT NOT NULL,
  `customer_id` INT NOT NULL,
  `car_id` INT NOT NULL,
  `date_processed` DATETIME NOT NULL,
  `rent_start_date` TIMESTAMP NOT NULL,
  `rent_end_date` TIMESTAMP NOT NULL,
  `days` INT NOT NULL,
  `rate_applied` FLOAT NOT NULL,
  `order_total` FLOAT NOT NULL,
  `order_status` TINYINT NOT NULL,
  PRIMARY KEY (`order_id`),
  INDEX `employee_id_idx` (`employee_id` ASC) VISIBLE,
  INDEX `customer_id_idx` (`customer_id` ASC) VISIBLE,
  INDEX `car_id_idx` (`car_id` ASC) VISIBLE,
  CONSTRAINT `employee_id`
    FOREIGN KEY (`employee_id`)
    REFERENCES `CarRental`.`employees` (`employee_id`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE,
  CONSTRAINT `customer_id`
    FOREIGN KEY (`customer_id`)
    REFERENCES `CarRental`.`customers` (`customer_id`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE,
  CONSTRAINT `car_id`
    FOREIGN KEY (`car_id`)
    REFERENCES `CarRental`.`cars` (`car_id`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
